header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: FeatureProbe

  paths:
    - 'featureprobe/**/*.py'
    - 'tests/**/*.py'
    - 'setup.py'
    - 'setup.cfg'
    - 'conftest.py'

  paths-ignore:
    - '**/*.md'

  comment: on-failure
