name: "Check license & format"

on:
  pull_request_target:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check license headers
        uses: apache/skywalking-eyes@v0.3.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            config: .github/licenserc.yml
            mode: check

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Check code format
        run: |
          pip install black
          python3 -m black --check .