name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
          ignoreLabels: |
            bot
            ignore-semantic-pull-request

      - name: Hint valid formats
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Please adjust your PR title to match the [Conventional Commits spec](https://www.conventionalcommits.org/).
            
            For example:
            - fix: fix http client code 
            - feat: allow provided config object to extend other configs
            - refactor!: drop support for node 6
            - feat(ui): add button component
