name: "Tests"

on:
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run:
    strategy:
      matrix:
        python: [ '3.5', '3.6', '3.7', '3.8', '3.9', '3.10' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests and collect coverage
        run: pytest --cov featureprobe

      - name: Upload coverage to Codecov
        if: ${{ matrix.python }} == '3.8'
        uses: codecov/codecov-action@v3
